language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  #- ROS_DISTRO=groovy ROSWS=rosws  BUILDER=rosbuild  USE_DEB=true
  - ROS_DISTRO=groovy ROSWS=rosws  BUILDER=rosbuild  USE_DEB=false
  #- ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin    USE_DEB=true
  - ROS_DISTRO=groovy ROSWS=wstool BUILDER=catkin    USE_DEB=false
  #- ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false
  #- ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false
matrix:
  allow_failures:
    - env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true
    - env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false
script: source .travis/travis.sh
notifications:
  recipients:
    - k-kojima@jsk.imi.i.u-tokyo.ac.jp
  email:
    on_success: always
    on_failure: always
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin
  - if [ $ROSWS == rosws ]; then sudo apt-get install -qq -y python-rosinstall     ; fi
  - if [ $BUILDER == rosbuild ]; then sudo apt-get install -qq -y ros-$ROS_DISTRO-rosmake ; fi
  # Setup rosdep
  - sudo rosdep init
  - rosdep update; while [ $? != 0 ]; do sleep 1; rosdep update; done
